language: clojure

script: docker run devth/yetibot lein test

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install docker-engine
  - ./scripts/docker.sh
