language: clojure

lein: lein2

script: lein2 test

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker version
  - lein docker build
  - lein docker push
