language: clojure

cache:
  directories:
    - $HOME/.m2

script: lein test

jdk:
  - oraclejdk8

sudo: required

services:
  - docker

after_success:
- CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage --codecov
- bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
# - sudo apt-get update
# - sudo apt-get install -y docker-engine
- ./scripts/docker.sh

addons:
  code_climate:
    repo_token: $CODE_CLIMATE_REPO_TOKEN
